name: water_tracker
description: "A tracker app for water intake and hydration goals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  provider: ^6.1.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

